export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FILTER_PRODUCTS_BY_SIZE = "FILTER_PRODUCTS_BY_SIZE";
export const ORDER_PRODUCTS_BY_PRICE = "ORDER_PRODUCTS_BY_PRICE";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const FILTER_PRODUCTS_BY_CATEGORY = "FILTER_PRODUCTS_BY_CATEGORY";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// export const userConstants = {
//     REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
//     REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
//     REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

//     LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
//     LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
//     LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

//     LOGOUT: 'USERS_LOGOUT',

//     GETALL_REQUEST: 'USERS_GETALL_REQUEST',
//     GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
//     GETALL_FAILURE: 'USERS_GETALL_FAILURE',

//     DELETE_REQUEST: 'USERS_DELETE_REQUEST',
//     DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
//     DELETE_FAILURE: 'USERS_DELETE_FAILURE'    
// };

export const alertConstants = {
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR'
};

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGOUT = 'LOGOUT';

export const SET_USER_PROFILE='SET_USER_PROFILE';
export const UPDATE_USER_PROFILE='UPDATE_USER_PROFILE';

